# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Assignment3' do
    pod 'AFNetworking', '3.0.0'
    pod 'BDBOAuth1Manager', '2.0.0'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

end

